language: node_js
sudo: true
node_js:
- stable
cache:
  directories:
  - site/bower_components
script:
- npm install -g polymer-cli
- npm install -g bower
- npm install -g firebase-tools
- cd site && bower install
- sleep 5
- cd ..
after_success:
  - ./firebase login --reauth
  - ./firebase_deploy.sh $TRAVIS_BRANCH $FIREBASE_TOKEN_PROD $FIREBASE_PROJECT_PROD
