language: node_js
sudo: true
node_js:
- stable
cache:
  directories:
  - site/bower_components
script:
- npm install -g polymer-cli
- npm install -g bower
- npm install -g firebase-tools
- cd site && bower install
- sleep 5
after_success:
- ./firebase_deploy.sh $TRAVIS_BRANCH $FIREBASE_PROJECT_PHIL $FIREBASE_TOKEN_PHIL $FIREBASE_TOKEN_PROD $FIREBASE_PROJECT_PROD